//! Emission and transition abstractions, and the Viterbi pass that turns
//! per-position model output into ranked candidate sentences.
//!
//! The pass is deliberately ignorant of where its scores come from. A
//! non-autoregressive model emits every position at once and so cannot express
//! that 中国 is likelier than 中过 -- the two differ only in how the second
//! position agrees with the first, which is exactly what conditional
//! independence throws away. Restoring it is a search over the same masks the
//! model was constrained by, with a transition term supplying the agreement. The
//! n-gram baseline is the same search with the emission term switched off
//! ([`Uniform`]), which is what makes the two routes comparable.

mod beam;
mod candidates;
mod emissions;
mod score;

pub use beam::{BeamOptions, Hypothesis, decode};
pub use candidates::{CandidatePath, Candidates};
pub use emissions::{
    EmissionError, Emittable, LatticePath, LatticeRecord, ScoreRecord, Scored, Weighted,
};
pub use score::{Emission, History, MAX_HISTORY, NoTransition, Transition, Uniform};

use thiserror::Error;

/// Why a typed string could not be decoded.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum DecodeError {
    /// The segmentation lattice produced nothing to decode.
    #[error("no segmentation to decode")]
    NoSegmentations,
    /// A segmentation had no character positions.
    #[error("segmentation {path} has no character positions")]
    EmptySegmentation {
        /// Index of the offending segmentation.
        path: usize,
    },
    /// A position admitted no character, which means the syllable table and the
    /// character lexicon were not generated by the same run.
    #[error("position {position} of segmentation {path} admits no character")]
    EmptyCandidateSet {
        /// Index of the offending segmentation.
        path: usize,
        /// Index of the offending position within it.
        position: usize,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use ime_pinyin::{CharId, Lexicon, SegmentLattice, SegmentOptions, SyllableTable};
    use std::collections::HashMap;

    fn fixture() -> (SyllableTable, Lexicon) {
        let table = SyllableTable::load();
        let lexicon = Lexicon::load(&table).expect("generated tables must agree");
        (table, lexicon)
    }

    fn offline() -> SegmentOptions {
        SegmentOptions {
            allow_incomplete_tail: false,
            ..SegmentOptions::default()
        }
    }

    fn candidates(input: &str, table: &SyllableTable, lexicon: &Lexicon) -> Candidates {
        let options = offline();
        let lattice = SegmentLattice::build(input, table, &options).expect("input reads");
        Candidates::build(&lattice.k_best(&options), lexicon).expect("masks are non-empty")
    }

    /// A transition model that likes exactly one sentence: each character in the
    /// table scores well after its listed predecessor, everything else scores
    /// badly. Enough to prove the search finds what the scores point at.
    struct Preference {
        bigrams: HashMap<(Option<CharId>, CharId), f32>,
    }

    impl Preference {
        fn new(lexicon: &Lexicon, sentence: &str) -> Self {
            let ids: Vec<CharId> = sentence
                .chars()
                .map(|ch| lexicon.id_of(ch).expect("sentence is in the lexicon"))
                .collect();
            let mut bigrams = HashMap::new();
            let mut previous = None;
            for id in ids {
                bigrams.insert((previous, id), 0.0);
                previous = Some(id);
            }
            Self { bigrams }
        }
    }

    impl Transition for Preference {
        const HISTORY: usize = 1;

        fn score(&self, history: History, candidate: CharId) -> f32 {
            *self
                .bigrams
                .get(&(history.back(1), candidate))
                .unwrap_or(&-10.0)
        }

        fn finish(&self, _history: History) -> f32 {
            0.0
        }
    }

    #[test]
    fn candidate_masks_match_the_segmentation_lengths() {
        let (table, lexicon) = fixture();
        let batch = candidates("zhongguo", &table, &lexicon);
        assert!(!batch.is_empty());
        for path in batch.paths() {
            assert!(!path.is_empty());
            assert!(path.positions().iter().all(|p| !p.is_empty()));
        }
    }

    #[test]
    fn the_search_recovers_the_sentence_the_scores_point_at() {
        let (table, lexicon) = fixture();
        let batch = candidates("zhongguo", &table, &lexicon);
        let transition = Preference::new(&lexicon, "中国");
        let best = decode(&batch, &Uniform, &transition, &BeamOptions::default())
            .expect("the batch decodes");
        assert_eq!(best[0].text(&lexicon), "中国");
    }

    #[test]
    fn hypotheses_are_ranked_and_unique() {
        let (table, lexicon) = fixture();
        let batch = candidates("nihao", &table, &lexicon);
        let transition = Preference::new(&lexicon, "你好");
        let best =
            decode(&batch, &Uniform, &transition, &BeamOptions::default()).expect("nihao decodes");
        assert!(best.len() > 1, "expected several hypotheses");
        assert!(
            best.windows(2).all(|w| w[0].score() >= w[1].score()),
            "hypotheses must come back sorted"
        );
        let texts: Vec<String> = best.iter().map(|h| h.text(&lexicon)).collect();
        let mut unique = texts.clone();
        unique.sort_unstable();
        unique.dedup();
        assert_eq!(unique.len(), texts.len(), "duplicates survived: {texts:?}");
    }

    #[test]
    fn top_k_is_honoured() {
        let (table, lexicon) = fixture();
        let batch = candidates("nihao", &table, &lexicon);
        let transition = Preference::new(&lexicon, "你好");
        let options = BeamOptions {
            top_k: std::num::NonZeroUsize::new(3).expect("3 is not zero"),
            ..BeamOptions::default()
        };
        let best = decode(&batch, &Uniform, &transition, &options).expect("nihao decodes");
        assert_eq!(best.len(), 3);
    }

    #[test]
    fn a_wider_beam_never_scores_worse() {
        let (table, lexicon) = fixture();
        let batch = candidates("zhongguorenmin", &table, &lexicon);
        let transition = Preference::new(&lexicon, "中国人民");
        let narrow = BeamOptions {
            beam_width: std::num::NonZeroUsize::new(1).expect("1 is not zero"),
            ..BeamOptions::default()
        };
        let wide = BeamOptions {
            beam_width: std::num::NonZeroUsize::new(64).expect("64 is not zero"),
            ..BeamOptions::default()
        };
        let narrow = decode(&batch, &Uniform, &transition, &narrow).expect("decodes");
        let wide = decode(&batch, &Uniform, &transition, &wide).expect("decodes");
        assert!(wide[0].score() >= narrow[0].score());
    }

    #[test]
    fn emission_scores_can_override_the_transition_model() {
        struct Insist(CharId);
        impl Emission for Insist {
            fn score(&self, _path: usize, _position: usize, candidate: CharId) -> f32 {
                if candidate == self.0 { 100.0 } else { 0.0 }
            }
        }
        let (table, lexicon) = fixture();
        let batch = candidates("zhong", &table, &lexicon);
        let zhong = lexicon.id_of('钟').expect("钟");
        let transition = Preference::new(&lexicon, "中");
        let best = decode(&batch, &Insist(zhong), &transition, &BeamOptions::default())
            .expect("zhong decodes");
        assert_eq!(best[0].text(&lexicon), "钟");
    }

    #[test]
    fn an_empty_batch_is_rejected() {
        let (_, lexicon) = fixture();
        assert_eq!(
            Candidates::build(&[], &lexicon).expect_err("an empty batch is an error"),
            DecodeError::NoSegmentations
        );
    }
}
