//! Emission and transition abstractions, and the Viterbi pass that turns
//! per-position model output into ranked candidate sentences.
//!
//! The pass is deliberately ignorant of where its scores come from. A
//! non-autoregressive model emits every position at once and so cannot express
//! that 中国 is likelier than 中过 -- the two differ only in how the second
//! position agrees with the first, which is exactly what conditional
//! independence throws away. Restoring it is a search over the same masks the
//! model was constrained by, with a transition term supplying the agreement. The
//! n-gram baseline is the same search with the emission term switched off
//! ([`Uniform`]), which is what makes the two routes comparable.

mod beam;
mod candidates;
mod emissions;
mod score;

pub use beam::{BeamOptions, Breakdown, Hypothesis, Record, decode_many, decode_many_stats};
pub use candidates::{CandidatePath, Candidates};
pub use emissions::{
    EmissionError, Emittable, LatticePath, LatticeRecord, ScoreRecord, Scored, Weighted,
    lattice_paths,
};
pub use score::{Asked, Both, Emission, History, MAX_HISTORY, NoTransition, Transition, Uniform};

use thiserror::Error;

/// Why a typed string could not be decoded.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum DecodeError {
    /// The segmentation lattice produced nothing to decode.
    #[error("no segmentation to decode")]
    NoSegmentations,
    /// A segmentation had no character positions.
    #[error("segmentation {path} has no character positions")]
    EmptySegmentation {
        /// Index of the offending segmentation.
        path: usize,
    },
    /// A position admitted no character, which means the syllable table and the
    /// character lexicon were not generated by the same run.
    #[error("position {position} of segmentation {path} admits no character")]
    EmptyCandidateSet {
        /// Index of the offending segmentation.
        path: usize,
        /// Index of the offending position within it.
        position: usize,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use ime_pinyin::{CharId, Lexicon, SegmentLattice, SegmentOptions, SyllableTable};
    use std::collections::HashMap;

    fn fixture() -> (SyllableTable, Lexicon) {
        let table = SyllableTable::load();
        let lexicon = Lexicon::load(&table).expect("generated tables must agree");
        (table, lexicon)
    }

    fn offline() -> SegmentOptions {
        SegmentOptions {
            allow_incomplete_tail: false,
            ..SegmentOptions::default()
        }
    }

    fn candidates(input: &str, table: &SyllableTable, lexicon: &Lexicon) -> Candidates {
        let options = offline();
        let lattice = SegmentLattice::build(input, table, &options).expect("input reads");
        Candidates::build(&lattice.k_best(&options), lexicon).expect("masks are non-empty")
    }

    /// `decode_many` over one record, as every call here decodes only one.
    fn decode<E: Emission, T: Transition>(
        batch: &Candidates,
        emission: E,
        transition: &T,
        context: Option<&str>,
        options: &BeamOptions,
    ) -> Result<Vec<Hypothesis>, DecodeError> {
        decode_many(
            &[Record {
                candidates: batch,
                emission,
                context,
            }],
            transition,
            options,
        )
        .map(|mut results| results.pop().expect("one record decodes to one result"))
    }

    /// A transition model that likes exactly one sentence: each character in the
    /// table scores well after its listed predecessor, everything else scores
    /// badly. Enough to prove the search finds what the scores point at.
    struct Preference {
        bigrams: HashMap<(Option<CharId>, CharId), f32>,
    }

    impl Preference {
        fn new(lexicon: &Lexicon, sentence: &str) -> Self {
            let ids: Vec<CharId> = sentence
                .chars()
                .map(|ch| lexicon.id_of(ch).expect("sentence is in the lexicon"))
                .collect();
            let mut bigrams = HashMap::new();
            let mut previous = None;
            for id in ids {
                bigrams.insert((previous, id), 0.0);
                previous = Some(id);
            }
            Self { bigrams }
        }
    }

    impl Transition for Preference {
        const HISTORY: usize = 1;

        type State = Option<CharId>;

        fn start(&self, _context: Option<&str>, _asked: &Asked<'_>) -> Self::State {
            None
        }

        fn score(&self, state: &Self::State, candidate: CharId) -> f32 {
            *self.bigrams.get(&(*state, candidate)).unwrap_or(&-10.0)
        }

        fn finish(&self, _state: &Self::State) -> f32 {
            0.0
        }

        fn advance(&self, steps: &[(&Self::State, CharId, Asked<'_>)]) -> Vec<Self::State> {
            steps.iter().map(|(_, ch, _)| Some(*ch)).collect()
        }
    }

    #[test]
    fn candidate_masks_match_the_segmentation_lengths() {
        let (table, lexicon) = fixture();
        let batch = candidates("zhongguo", &table, &lexicon);
        assert!(!batch.is_empty());
        for path in batch.paths() {
            assert!(!path.is_empty());
            assert!(path.positions().iter().all(|p| !p.is_empty()));
        }
    }

    #[test]
    fn the_search_recovers_the_sentence_the_scores_point_at() {
        let (table, lexicon) = fixture();
        let batch = candidates("zhongguo", &table, &lexicon);
        let transition = Preference::new(&lexicon, "中国");
        let best = decode(&batch, Uniform, &transition, None, &BeamOptions::default())
            .expect("the batch decodes");
        assert_eq!(best[0].text(&lexicon), "中国");
    }

    #[test]
    fn hypotheses_are_ranked_and_unique() {
        let (table, lexicon) = fixture();
        let batch = candidates("nihao", &table, &lexicon);
        let transition = Preference::new(&lexicon, "你好");
        let best = decode(&batch, Uniform, &transition, None, &BeamOptions::default())
            .expect("nihao decodes");
        assert!(best.len() > 1, "expected several hypotheses");
        assert!(
            best.windows(2).all(|w| w[0].score() >= w[1].score()),
            "hypotheses must come back sorted"
        );
        let texts: Vec<String> = best.iter().map(|h| h.text(&lexicon)).collect();
        let mut unique = texts.clone();
        unique.sort_unstable();
        unique.dedup();
        assert_eq!(unique.len(), texts.len(), "duplicates survived: {texts:?}");
    }

    #[test]
    fn top_k_is_honoured() {
        let (table, lexicon) = fixture();
        let batch = candidates("nihao", &table, &lexicon);
        let transition = Preference::new(&lexicon, "你好");
        let options = BeamOptions {
            top_k: std::num::NonZeroUsize::new(3).expect("3 is not zero"),
            ..BeamOptions::default()
        };
        let best = decode(&batch, Uniform, &transition, None, &options).expect("nihao decodes");
        assert_eq!(best.len(), 3);
    }

    #[test]
    fn a_wider_beam_never_scores_worse() {
        let (table, lexicon) = fixture();
        let batch = candidates("zhongguorenmin", &table, &lexicon);
        let transition = Preference::new(&lexicon, "中国人民");
        let narrow = BeamOptions {
            beam_width: std::num::NonZeroUsize::new(1).expect("1 is not zero"),
            ..BeamOptions::default()
        };
        let wide = BeamOptions {
            beam_width: std::num::NonZeroUsize::new(64).expect("64 is not zero"),
            ..BeamOptions::default()
        };
        let narrow = decode(&batch, Uniform, &transition, None, &narrow).expect("decodes");
        let wide = decode(&batch, Uniform, &transition, None, &wide).expect("decodes");
        assert!(wide[0].score() >= narrow[0].score());
    }

    #[test]
    fn emission_scores_can_override_the_transition_model() {
        struct Insist(CharId);
        impl Emission for Insist {
            fn score(&self, _path: usize, _position: usize, candidate: CharId) -> f32 {
                if candidate == self.0 { 100.0 } else { 0.0 }
            }
        }
        let (table, lexicon) = fixture();
        let batch = candidates("zhong", &table, &lexicon);
        let zhong = lexicon.id_of('钟').expect("钟");
        let transition = Preference::new(&lexicon, "中");
        let best = decode(
            &batch,
            Insist(zhong),
            &transition,
            None,
            &BeamOptions::default(),
        )
        .expect("zhong decodes");
        assert_eq!(best[0].text(&lexicon), "钟");
    }

    #[test]
    fn a_batch_decodes_each_record_as_if_alone() {
        let (table, lexicon) = fixture();
        let batches = [
            candidates("zhongguo", &table, &lexicon),
            candidates("nihao", &table, &lexicon),
        ];
        let transition = Preference::new(&lexicon, "中国");
        let options = BeamOptions::default();
        let together = decode_many(
            &batches
                .iter()
                .map(|batch| Record {
                    candidates: batch,
                    emission: Uniform,
                    context: None,
                })
                .collect::<Vec<_>>(),
            &transition,
            &options,
        )
        .expect("the batch decodes");
        assert_eq!(together.len(), batches.len());
        for (batch, results) in batches.iter().zip(&together) {
            let alone = decode(batch, Uniform, &transition, None, &options).expect("decodes");
            assert_eq!(results.len(), alone.len());
            for (batched, solo) in results.iter().zip(&alone) {
                assert_eq!(batched.chars(), solo.chars());
                assert_eq!(
                    batched.score().to_bits(),
                    solo.score().to_bits(),
                    "a batched record scores bit-identically to the solo run"
                );
                assert_eq!(batched.path(), solo.path());
            }
        }
    }

    #[test]
    fn the_list_keeps_the_runner_up_first_character() {
        struct PerPosition {
            scores: HashMap<(usize, CharId), f32>,
        }
        impl Emission for PerPosition {
            fn score(&self, _path: usize, position: usize, candidate: CharId) -> f32 {
                *self.scores.get(&(position, candidate)).unwrap_or(&-20.0)
            }
        }
        /// Scores nothing and remembers two characters, so prefixes that
        /// diverge at position 0 are not merged away before they can finish.
        struct Flat;
        impl Transition for Flat {
            const HISTORY: usize = 2;
            type State = ();
            fn start(&self, _context: Option<&str>, _asked: &Asked<'_>) -> Self::State {}
            fn score(&self, _state: &Self::State, _candidate: CharId) -> f32 {
                0.0
            }
            fn finish(&self, _state: &Self::State) -> f32 {
                0.0
            }
            fn advance(&self, steps: &[(&Self::State, CharId, Asked<'_>)]) -> Vec<Self::State> {
                vec![(); steps.len()]
            }
        }
        let (table, lexicon) = fixture();
        let batch = candidates("tashi", &table, &lexicon);
        let ta = lexicon.id_of('他').expect("他");
        let ta2 = lexicon.id_of('她').expect("她");
        // `tashi` reads as `ta` + `shi`; the second position admits enough
        // characters for the stronger first character's tails to fill top-8.
        let path = batch
            .paths()
            .iter()
            .find(|path| path.len() == 2)
            .expect("tashi reads as two syllables");
        let second = &path.positions()[1];
        assert!(second.len() >= 10, "the fixture needs a wide tail");
        assert!(path.positions()[0].contains(&ta2));
        let mut scores = HashMap::new();
        // The runner-up is close behind, and at least eight of the winner's
        // tails are closer -- so a score-ordered top-8 cannot reach it, while
        // the 16-wide beam still carries it to the end.
        scores.insert((0, ta), 0.0);
        scores.insert((0, ta2), -0.2);
        let mut tail = 0.0f32;
        for &ch in second {
            scores.insert((1, ch), tail);
            tail -= 0.02;
        }
        let best = decode(
            &batch,
            PerPosition { scores },
            &Flat,
            None,
            &BeamOptions::default(),
        )
        .expect("tashi decodes");
        assert_eq!(best[0].chars()[0], ta, "top-1 stays the best hypothesis");
        assert!(
            best.iter().any(|h| h.chars()[0] == ta2),
            "the runner-up reading of position 0 is listed: {:?}",
            best.iter().map(|h| h.text(&lexicon)).collect::<Vec<_>>()
        );
    }

    #[test]
    fn the_beam_keeps_a_runner_up_reading_alive() {
        struct PerPosition {
            scores: HashMap<(usize, CharId), f32>,
        }
        impl Emission for PerPosition {
            fn score(&self, _path: usize, position: usize, candidate: CharId) -> f32 {
                *self.scores.get(&(position, candidate)).unwrap_or(&-20.0)
            }
        }
        let (table, lexicon) = fixture();
        let batch = candidates("tashi", &table, &lexicon);
        let ta = lexicon.id_of('他').expect("他");
        let ta2 = lexicon.id_of('她').expect("她");
        let path = batch
            .paths()
            .iter()
            .find(|path| path.len() == 2)
            .expect("tashi reads as two syllables");
        let second = &path.positions()[1];
        // `她` trails `他` by 0.2 at position 0, and every `他` tail beats
        // every `她` tail, so under a one-character history each `她x`
        // merges into `他x` -- without a guard no `她` state can reach
        // position 1 at all.
        assert!(second.len() >= 10, "the fixture needs a wide tail");
        assert!(path.positions()[0].contains(&ta2));
        let mut scores = HashMap::new();
        scores.insert((0, ta), 0.0);
        scores.insert((0, ta2), -0.2);
        let mut tail = 0.0f32;
        for &ch in second {
            scores.insert((1, ch), tail);
            tail -= 0.02;
        }
        let narrow = BeamOptions {
            diversity_gap: 0.0,
            ..BeamOptions::default()
        };
        let plain = decode(
            &batch,
            PerPosition {
                scores: scores.clone(),
            },
            &NoTransition,
            None,
            &narrow,
        )
        .expect("tashi decodes");
        assert!(
            plain.iter().all(|h| h.chars()[0] == ta),
            "without the guard every survivor reads the winner's character: {:?}",
            plain.iter().map(|h| h.text(&lexicon)).collect::<Vec<_>>()
        );
        let guarded = BeamOptions {
            diversity_gap: 0.5,
            diversity_chars: 2,
            ..BeamOptions::default()
        };
        let best = decode(
            &batch,
            PerPosition { scores },
            &NoTransition,
            None,
            &guarded,
        )
        .expect("tashi decodes");
        assert_eq!(best[0].chars()[0], ta, "top-1 stays the best hypothesis");
        assert!(
            best.iter().any(|h| h.chars()[0] == ta2),
            "the guarded runner-up survives the beam and reaches the list: {:?}",
            best.iter().map(|h| h.text(&lexicon)).collect::<Vec<_>>()
        );
    }

    #[test]
    fn an_empty_batch_is_rejected() {
        let (_, lexicon) = fixture();
        assert_eq!(
            Candidates::build(&[], &lexicon).expect_err("an empty batch is an error"),
            DecodeError::NoSegmentations
        );
    }

}
