//! `corrections(span)`: the syllables the typo noise model can bend into a span.
//!
//! This is the inference half of typo tolerance (#104): for a typed span `s`,
//! every syllable `y` the noise model in `data/typo.json` can turn into `s`
//! within at most two edits, costed `-log P(s | y)` where `P(s | y)` sums the
//! probability of every one- and two-edit path that produces `s` -- the
//! edit-count distribution and the per-sentence coin do not enter it, only the
//! per-edit draws. It is a port of `mlime.typo.CorrectionTable`; the fixture at
//! `tests/fixtures/typo-corrections.json` holds the two to the same numbers.
//!
//! When `s` is itself a valid syllable or a syllable prefix (the abbreviation
//! case), `s` appears in its own list at cost 0: reading the typed letters as
//! meant is always an option the decoder may price. Entries sort by cost with
//! the syllable breaking ties, and at most `K` of them survive -- the cap is
//! what keeps a high-entropy typo from exploding the candidate union.
//!
//! The five edit operations mirror the model's: a letter substituted by a
//! QWERTY neighbour, two neighbouring letters transposed, a letter omitted, a
//! letter doubled, and a fuzzy pair swapped at a syllable's initial or final.

use std::collections::{HashMap, HashSet};
use std::sync::RwLock;

use serde::Deserialize;
use thiserror::Error;

use crate::syllable::SyllableTable;

/// The shared noise table, generated by `mlime gen-pinyin-tables` next to the
/// syllable inventory it describes errors over; never edited by hand.
const TYPO_MODEL: &str = include_str!("../data/typo.json");

/// The letter a letter is: `a`..`z` map to 0..25 in every table here.
const ALPHABET: usize = 26;

/// One directional fuzzy substitution and where inside a syllable it sits.
#[derive(Debug)]
struct FuzzyPair {
    /// What the typist meant (`zh` in `zha`).
    from: String,
    /// What a fuzzy swap produces (`z` in `za`).
    to: String,
    /// Whether the pair lives at the syllable's initial or its final.
    site: Site,
    /// The pair's share of a fuzzy draw among the sites the string admits.
    weight: f64,
}

/// Whether a fuzzy pair replaces a syllable's initial or its final.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
enum Site {
    /// The syllable's initial consonant (`zh` in `zhong`).
    Initial,
    /// The syllable's final (`an` in `zhan`).
    Final,
}

/// One fuzzy-pair entry of the generated table.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawPair {
    from: String,
    to: String,
    #[serde(rename = "where")]
    site: String,
    weight: f64,
}

/// The `edit_type` section: each kind's share of one edit draw.
#[derive(Copy, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct EditWeights {
    adjacent: f64,
    transposition: f64,
    omission: f64,
    doubling: f64,
    fuzzy: f64,
}

/// The generated `typo.json`, as serde reads it.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawModel {
    per_sentence: f64,
    edit_count: HashMap<String, f64>,
    edit_type: EditWeights,
    initials: Vec<String>,
    neighbours: HashMap<String, String>,
    fuzzy_pairs: Vec<RawPair>,
}

/// Why the embedded noise table could not be read.
///
/// The table is shared with the Python side, whose `NoiseModel.parse` refuses
/// the same shapes; the two parsers never disagree about validity.
#[derive(Debug, Error)]
pub enum NoiseError {
    /// The JSON did not parse, or a field held the wrong shape.
    #[error("the typo table is malformed: {0}")]
    Malformed(String),
}

/// The noise model read from `typo.json`: the edit-type rates and the letter
/// tables the operations draw from. `per_sentence` and `edit_count` are checked
/// at parse and dropped -- a `corrections` cost prices per-edit draws only.
struct NoiseModel {
    edit_type: EditWeights,
    initials: HashSet<String>,
    /// `neighbours[i]` are the keys a finger can slip to from letter `i`.
    neighbours: [Box<[u8]>; ALPHABET],
    fuzzy_pairs: Vec<FuzzyPair>,
}

/// Each edit kind's probability at a string, normalised the way the model's
/// draw normalises it: kinds the string does not admit carry 0.
#[derive(Copy, Clone)]
struct Kinds {
    adjacent: f64,
    transposition: f64,
    omission: f64,
    doubling: f64,
    fuzzy: f64,
}

/// The `initials` section: every entry a word, `zh`/`ch`/`sh` always among it.
fn parse_initials(entries: &[String]) -> Result<HashSet<String>, NoiseError> {
    let mut initials = HashSet::with_capacity(entries.len());
    for (index, item) in entries.iter().enumerate() {
        if !is_word(item) {
            return Err(NoiseError::Malformed(format!(
                "initials[{index}] must be an [a-z] string, got {item:?}"
            )));
        }
        initials.insert(item.clone());
    }
    for initial in ["zh", "ch", "sh"] {
        if !initials.contains(initial) {
            return Err(NoiseError::Malformed(format!(
                "initials must include {initial:?}"
            )));
        }
    }
    Ok(initials)
}

/// The `neighbours` section: exactly [a-z] keys, a symmetric table with no
/// self-loops and no repeats.
fn parse_neighbours(
    entries: &HashMap<String, String>,
) -> Result<[Box<[u8]>; ALPHABET], NoiseError> {
    let mut neighbours: [Box<[u8]>; ALPHABET] = std::array::from_fn(|_| Box::default());
    if entries.len() != ALPHABET {
        return Err(NoiseError::Malformed(
            "neighbours must cover exactly [a-z]".to_owned(),
        ));
    }
    for (key, near) in entries {
        let bytes = key.as_bytes();
        let [letter] = *bytes else {
            return Err(NoiseError::Malformed(format!(
                "a neighbour key must be one letter, got {key:?}"
            )));
        };
        if !letter.is_ascii_lowercase() || !is_word(near) {
            return Err(NoiseError::Malformed(format!(
                "neighbours[{key:?}] must be [a-z] letters, got {near:?}"
            )));
        }
        if near.as_bytes().contains(&letter) {
            return Err(NoiseError::Malformed(format!(
                "{key:?} is its own neighbour"
            )));
        }
        if near.len() != near.bytes().collect::<HashSet<_>>().len() {
            return Err(NoiseError::Malformed(format!(
                "neighbours[{key:?}] repeats a key: {near:?}"
            )));
        }
        neighbours[usize::from(letter - b'a')] = near.as_bytes().into();
    }
    for (key, near) in entries {
        let letter = key.as_bytes()[0];
        for &other in near.as_bytes() {
            if !neighbours[usize::from(other - b'a')].contains(&letter) {
                return Err(NoiseError::Malformed(format!(
                    "{key:?} neighbours {other:?} but not vice versa"
                )));
            }
        }
    }
    Ok(neighbours)
}

/// The `fuzzy_pairs` section: unique directed pairs, each weighted and bound
/// to one site; an initial-side pair's `from` must be a real initial.
fn parse_fuzzy_pairs(
    entries: &[RawPair],
    initials: &HashSet<String>,
) -> Result<Vec<FuzzyPair>, NoiseError> {
    let mut pairs = Vec::with_capacity(entries.len());
    let mut seen = HashSet::new();
    for (index, entry) in entries.iter().enumerate() {
        let where_ = format!("fuzzy_pairs[{index}]");
        if !is_word(&entry.from) || !is_word(&entry.to) {
            return Err(NoiseError::Malformed(format!(
                "{where_}: the pair must be [a-z] strings"
            )));
        }
        if entry.weight <= 0.0 {
            return Err(NoiseError::Malformed(format!(
                "{where_}: a fuzzy weight must be positive, got {}",
                entry.weight
            )));
        }
        let site = match entry.site.as_str() {
            "initial" => Site::Initial,
            "final" => Site::Final,
            other => {
                return Err(NoiseError::Malformed(format!(
                    "{where_}: a pair sits at 'initial' or 'final', got {other:?}"
                )));
            }
        };
        if entry.from == entry.to {
            return Err(NoiseError::Malformed(format!(
                "{where_}: the pair {:?} maps to itself",
                entry.from
            )));
        }
        if site == Site::Initial && !initials.contains(&entry.from) {
            return Err(NoiseError::Malformed(format!(
                "{where_}: {:?} is not one of the initials",
                entry.from
            )));
        }
        if !seen.insert((entry.from.clone(), entry.to.clone())) {
            return Err(NoiseError::Malformed(format!(
                "{where_}: the pair {:?}->{:?} is duplicated",
                entry.from, entry.to
            )));
        }
        pairs.push(FuzzyPair {
            from: entry.from.clone(),
            to: entry.to.clone(),
            site,
            weight: entry.weight,
        });
    }
    Ok(pairs)
}

fn is_word(field: &str) -> bool {
    !field.is_empty() && field.bytes().all(|byte| byte.is_ascii_lowercase())
}

/// A value in the table that must be a probability.
fn probability(value: f64, where_: &str) -> Result<f64, NoiseError> {
    if !(0.0..=1.0).contains(&value) {
        return Err(NoiseError::Malformed(format!(
            "{where_} must be a probability, got {value}"
        )));
    }
    Ok(value)
}

/// A set of rates that must sum to one.
fn check_distribution(weights: impl Iterator<Item = f64>, where_: &str) -> Result<(), NoiseError> {
    let total: f64 = weights.sum();
    if (total - 1.0).abs() > 1e-6 {
        return Err(NoiseError::Malformed(format!(
            "{where_} must be a distribution; it sums to {total}"
        )));
    }
    Ok(())
}

impl NoiseModel {
    /// Read the table, refusing anything malformed.
    fn parse(raw: &str) -> Result<Self, NoiseError> {
        let data: RawModel =
            serde_json::from_str(raw).map_err(|error| NoiseError::Malformed(error.to_string()))?;
        probability(data.per_sentence, "per_sentence")?;
        let mut counts = Vec::new();
        for (key, value) in &data.edit_count {
            let count: u32 = key
                .parse()
                .ok()
                .filter(|count| *count >= 1)
                .ok_or_else(|| {
                    NoiseError::Malformed(format!(
                        "an edit count must be a positive count, got {key:?}"
                    ))
                })?;
            counts.push(probability(*value, "edit_count entry")?);
            let _ = count;
        }
        check_distribution(data.edit_count.values().copied(), "edit_count")?;
        check_distribution(
            [
                data.edit_type.adjacent,
                data.edit_type.doubling,
                data.edit_type.fuzzy,
                data.edit_type.omission,
                data.edit_type.transposition,
            ]
            .into_iter()
            .map(|value| probability(value, "edit_type entry"))
            .collect::<Result<Vec<_>, _>>()?
            .into_iter(),
            "edit_type",
        )?;
        let initials = parse_initials(&data.initials)?;
        let neighbours = parse_neighbours(&data.neighbours)?;
        let fuzzy_pairs = parse_fuzzy_pairs(&data.fuzzy_pairs, &initials)?;
        Ok(Self {
            edit_type: data.edit_type,
            initials,
            neighbours,
            fuzzy_pairs,
        })
    }

    /// The syllable's initial: the longest initial prefix, or `""`.
    fn initial_of<'a>(&self, syllable: &'a str) -> &'a str {
        for length in [2, 1] {
            if syllable.len() >= length && self.initials.contains(&syllable[..length]) {
                return &syllable[..length];
            }
        }
        ""
    }

    /// The syllable's final: what its initial leaves.
    fn final_of<'a>(&self, syllable: &'a str) -> &'a str {
        &syllable[self.initial_of(syllable).len()..]
    }

    /// The fuzzy pairs the single-syllable string admits.
    fn sites(&self, letters: &str) -> Vec<&FuzzyPair> {
        self.fuzzy_pairs
            .iter()
            .filter(|pair| {
                (pair.site == Site::Initial && self.initial_of(letters) == pair.from)
                    || (pair.site == Site::Final && self.final_of(letters) == pair.from)
            })
            .collect()
    }

    /// The syllable after one fuzzy swap.
    fn apply_pair(letters: &str, pair: &FuzzyPair) -> String {
        match pair.site {
            Site::Initial => format!("{}{}", pair.to, &letters[pair.from.len()..]),
            Site::Final => format!("{}{}", &letters[..letters.len() - pair.from.len()], pair.to),
        }
    }

    /// The keys a slip off *letter* can land on.
    ///
    /// # Panics
    ///
    /// If *letter* is outside `[a-z]` -- the same refusal `neighbours[letter]`
    /// raises on the Python side.
    fn near(&self, letter: u8) -> &[u8] {
        let index = usize::from(letter.wrapping_sub(b'a'));
        &self.neighbours[index]
    }

    /// Each edit kind's probability at *letters*, normalised the way a draw is.
    fn applicable(&self, letters: &str) -> Kinds {
        let mut kinds = Kinds {
            adjacent: self.edit_type.adjacent,
            transposition: self.edit_type.transposition,
            omission: self.edit_type.omission,
            doubling: self.edit_type.doubling,
            fuzzy: if self.sites(letters).is_empty() {
                0.0
            } else {
                self.edit_type.fuzzy
            },
        };
        if letters.is_empty() {
            kinds = Kinds {
                adjacent: 0.0,
                transposition: 0.0,
                omission: 0.0,
                doubling: 0.0,
                fuzzy: 0.0,
            };
        } else if letters.len() < 2 {
            kinds.transposition = 0.0;
            kinds.omission = 0.0;
        }
        let total =
            kinds.adjacent + kinds.transposition + kinds.omission + kinds.doubling + kinds.fuzzy;
        Kinds {
            adjacent: kinds.adjacent / total,
            transposition: kinds.transposition / total,
            omission: kinds.omission / total,
            doubling: kinds.doubling / total,
            fuzzy: kinds.fuzzy / total,
        }
    }

    /// Every `(string, probability)` one edit of *letters* produces, duplicates
    /// merged.
    ///
    /// Ordered by first production, the way the Python dict the fixture's
    /// numbers were summed under iterates: `P(span | y)` adds each draw's
    /// share in this order, and a different order drifts the total by an ulp
    /// or two -- enough to reorder two corrections that sit at the same cost.
    fn outcomes(&self, letters: &str) -> Vec<(Box<str>, f64)> {
        let kinds = self.applicable(letters);
        let mut out: Vec<(Box<str>, f64)> = Vec::new();
        let mut add = |produced: Vec<u8>, probability: f64| {
            let produced: Box<str> = String::from_utf8(produced)
                .expect("edits move [a-z] letters only")
                .into_boxed_str();
            if let Some(entry) = out.iter_mut().find(|(held, _)| **held == *produced) {
                entry.1 += probability;
            } else {
                out.push((produced, probability));
            }
        };
        if kinds.adjacent != 0.0 {
            self.neighbour_outcomes(letters, kinds.adjacent, &mut add);
        }
        if kinds.transposition != 0.0 {
            Self::transposition_outcomes(letters, kinds.transposition, &mut add);
        }
        if kinds.omission != 0.0 {
            Self::omission_outcomes(letters, kinds.omission, &mut add);
        }
        if kinds.doubling != 0.0 {
            Self::doubling_outcomes(letters, kinds.doubling, &mut add);
        }
        if kinds.fuzzy != 0.0 {
            self.fuzzy_outcomes(letters, kinds.fuzzy, &mut add);
        }
        out
    }

    /// Every string one neighbour substitution of *letters* produces.
    #[expect(
        clippy::cast_precision_loss,
        reason = "span lengths stay far below 2^53"
    )]
    fn neighbour_outcomes(&self, letters: &str, kind: f64, add: &mut impl FnMut(Vec<u8>, f64)) {
        let bytes = letters.as_bytes();
        let each = kind / letters.len() as f64;
        for (index, &letter) in bytes.iter().enumerate() {
            let near = self.near(letter);
            for &replacement in near {
                let mut produced = bytes.to_vec();
                produced[index] = replacement;
                add(produced, each / near.len() as f64);
            }
        }
    }

    /// Every string one adjacent transposition of *letters* produces.
    #[expect(
        clippy::cast_precision_loss,
        reason = "span lengths stay far below 2^53"
    )]
    fn transposition_outcomes(letters: &str, kind: f64, add: &mut impl FnMut(Vec<u8>, f64)) {
        let bytes = letters.as_bytes();
        let each = kind / (letters.len() - 1) as f64;
        for index in 0..letters.len() - 1 {
            let mut produced = bytes.to_vec();
            produced.swap(index, index + 1);
            add(produced, each);
        }
    }

    /// Every string one omission of *letters* produces.
    #[expect(
        clippy::cast_precision_loss,
        reason = "span lengths stay far below 2^53"
    )]
    fn omission_outcomes(letters: &str, kind: f64, add: &mut impl FnMut(Vec<u8>, f64)) {
        let bytes = letters.as_bytes();
        let each = kind / letters.len() as f64;
        for index in 0..letters.len() {
            let mut produced = Vec::with_capacity(letters.len() - 1);
            produced.extend_from_slice(&bytes[..index]);
            produced.extend_from_slice(&bytes[index + 1..]);
            add(produced, each);
        }
    }

    /// Every string one doubling of *letters* produces.
    #[expect(
        clippy::cast_precision_loss,
        reason = "span lengths stay far below 2^53"
    )]
    fn doubling_outcomes(letters: &str, kind: f64, add: &mut impl FnMut(Vec<u8>, f64)) {
        let bytes = letters.as_bytes();
        let each = kind / letters.len() as f64;
        for index in 0..letters.len() {
            let mut produced = Vec::with_capacity(letters.len() + 1);
            produced.extend_from_slice(&bytes[..=index]);
            produced.push(bytes[index]);
            produced.extend_from_slice(&bytes[index + 1..]);
            add(produced, each);
        }
    }

    /// Every string one fuzzy swap of *letters* produces.
    fn fuzzy_outcomes(&self, letters: &str, kind: f64, add: &mut impl FnMut(Vec<u8>, f64)) {
        let sites = self.sites(letters);
        let weight: f64 = sites.iter().map(|pair| pair.weight).sum();
        for pair in sites {
            let produced = Self::apply_pair(letters, pair).into_bytes();
            add(produced, kind * pair.weight / weight);
        }
    }

    /// `P(produced | source)` when `produced` and `source` share a length:
    /// neighbour substitution, transposition (including a transposed pair of
    /// equal letters, which leaves the string untouched), or a fuzzy swap.
    #[expect(
        clippy::cast_precision_loss,
        reason = "span lengths stay far below 2^53"
    )]
    fn same_length_probability(&self, kinds: &Kinds, source: &str, produced: &str) -> f64 {
        let length = source.len();
        let source_bytes = source.as_bytes();
        let produced_bytes = produced.as_bytes();
        let diffs: Vec<usize> = source_bytes
            .iter()
            .zip(produced_bytes)
            .enumerate()
            .filter_map(|(index, (&left, &right))| (left != right).then_some(index))
            .collect();
        let mut probability = 0.0;
        if diffs.is_empty() && kinds.transposition != 0.0 {
            // Transposing a pair of equal letters is a real draw that
            // changes nothing.
            let hits = source_bytes
                .windows(2)
                .filter(|pair| pair[0] == pair[1])
                .count();
            probability += kinds.transposition * hits as f64 / (length - 1) as f64;
        }
        if diffs.len() == 1 {
            let index = diffs[0];
            let near = self.near(source_bytes[index]);
            if near.contains(&produced_bytes[index]) {
                probability += kinds.adjacent / length as f64 / near.len() as f64;
            }
        }
        if diffs.len() == 2 && diffs[1] == diffs[0] + 1 {
            let index = diffs[0];
            if source_bytes[index] == produced_bytes[index + 1]
                && source_bytes[index + 1] == produced_bytes[index]
            {
                probability += kinds.transposition / (length - 1) as f64;
            }
        }
        probability
    }

    /// `P(produced | source)` for one edit, summed over every way it can happen.
    #[expect(
        clippy::cast_precision_loss,
        reason = "span lengths stay far below 2^53"
    )]
    fn one_edit_probability(&self, source: &str, produced: &str) -> f64 {
        let kinds = self.applicable(source);
        let length = source.len();
        let source_bytes = source.as_bytes();
        let produced_bytes = produced.as_bytes();
        let mut probability = 0.0;
        if produced.len() == length {
            probability += self.same_length_probability(&kinds, source, produced);
        } else if produced.len() + 1 == length && kinds.omission != 0.0 {
            let hits = (0..length)
                .filter(|&index| {
                    produced_bytes[..index] == source_bytes[..index]
                        && produced_bytes[index..] == source_bytes[index + 1..]
                })
                .count();
            probability += kinds.omission * hits as f64 / length as f64;
        } else if produced.len() == length + 1 && kinds.doubling != 0.0 {
            let hits = (0..length)
                .filter(|&index| {
                    produced_bytes[..=index] == source_bytes[..=index]
                        && produced_bytes[index + 1] == source_bytes[index]
                        && produced_bytes[index + 2..] == source_bytes[index + 1..]
                })
                .count();
            probability += kinds.doubling * hits as f64 / length as f64;
        }
        if kinds.fuzzy != 0.0 {
            let sites = self.sites(source);
            let weight: f64 = sites.iter().map(|pair| pair.weight).sum();
            for pair in sites {
                if Self::apply_pair(source, pair) == produced {
                    probability += kinds.fuzzy * pair.weight / weight;
                }
            }
        }
        probability
    }

    /// Every string one edit could have become *produced* from, valid or not.
    ///
    /// The inverse of `outcomes`: adjacent and transposition are their own
    /// inverses (the neighbour table is symmetric by construction), omission
    /// inverts to inserting any letter anywhere, doubling inverts to deleting
    /// one letter of a repeated pair, and a fuzzy swap inverts to the pair's
    /// other direction at the same site.
    fn predecessors(&self, produced: &str) -> HashSet<Box<str>> {
        let length = produced.len();
        let bytes = produced.as_bytes();
        let mut out: HashSet<Box<str>> = HashSet::new();
        for (index, &letter) in bytes.iter().enumerate() {
            for &original in self.near(letter) {
                let mut source = bytes.to_vec();
                source[index] = original;
                out.insert(
                    String::from_utf8(source)
                        .expect("edits move [a-z] letters only")
                        .into_boxed_str(),
                );
            }
        }
        for index in 0..length.saturating_sub(1) {
            let mut source = bytes.to_vec();
            source.swap(index, index + 1);
            out.insert(
                String::from_utf8(source)
                    .expect("edits move [a-z] letters only")
                    .into_boxed_str(),
            );
        }
        for index in 0..=length {
            for letter in b'a'..=b'z' {
                let mut source = Vec::with_capacity(length + 1);
                source.extend_from_slice(&bytes[..index]);
                source.push(letter);
                source.extend_from_slice(&bytes[index..]);
                out.insert(
                    String::from_utf8(source)
                        .expect("edits move [a-z] letters only")
                        .into_boxed_str(),
                );
            }
        }
        for index in 1..length {
            if bytes[index] == bytes[index - 1] {
                let mut source = Vec::with_capacity(length - 1);
                source.extend_from_slice(&bytes[..index]);
                source.extend_from_slice(&bytes[index + 1..]);
                out.insert(
                    String::from_utf8(source)
                        .expect("edits move [a-z] letters only")
                        .into_boxed_str(),
                );
            }
        }
        for pair in &self.fuzzy_pairs {
            match pair.site {
                Site::Initial if self.initial_of(produced) == pair.to.as_str() => {
                    out.insert(
                        format!("{}{}", pair.from, &produced[pair.to.len()..]).into_boxed_str(),
                    );
                }
                Site::Final if self.final_of(produced) == pair.to.as_str() => {
                    out.insert(
                        format!(
                            "{}{}",
                            &produced[..produced.len() - pair.to.len()],
                            pair.from
                        )
                        .into_boxed_str(),
                    );
                }
                _ => {}
            }
        }
        out
    }
}

/// Corrections kept per typed span, per the shared #101 spec.
const CORRECTIONS_K: usize = 8;

/// The furthest the noise model reaches: `corrections` never offers a syllable
/// more than two edits away from the typed span.
pub const CORRECTIONS_MAX_EDITS: usize = 2;

/// One `corrections` entry: a syllable the span can be a corruption of, and the
/// cost of that reading.
#[derive(Clone, PartialEq, Debug)]
pub struct Correction {
    /// The syllable -- or the span itself, for the cost-0 self entry a valid
    /// syllable or prefix earns.
    span: Box<str>,
    /// `-log P(span | syllable)`; 0 for the self entry.
    cost: f64,
}

impl Correction {
    /// The spelling of the syllable this correction reads the span as.
    #[must_use]
    pub fn syllable(&self) -> &str {
        &self.span
    }

    /// `-log P(span | syllable)` under the noise model; 0 when the span is
    /// itself a valid syllable or prefix.
    #[must_use]
    pub const fn cost(&self) -> f64 {
        self.cost
    }
}

/// One span's full resolution: the capped entries, and every cost behind them.
///
/// The two products of one pass over the inventory share a memoised slot
/// because both are asked together: the lattice wants the `K` best, and the
/// candidate priors want every syllable's price, capped or not.
struct Resolved {
    /// The `K`-capped `(syllable, cost)` list `corrections` hands out.
    entries: std::sync::Arc<[Correction]>,
    /// Every syllable reaching the span within two edits, by table index,
    /// at `-log P(span | y)` -- the uncapped map `entries` truncates. A span
    /// that is itself a syllable holds its cost-0 self entry here too, in
    /// place of whatever its own paths priced it at.
    costs: std::sync::Arc<HashMap<usize, f64>>,
}

/// `corrections(span)`: the syllables the noise model can bend into *span*.
///
/// Built once per session against the syllable table; every query memoises,
/// because a session asks the same spans every keystroke.
pub struct CorrectionTable {
    /// The noise model the costs are priced under.
    model: NoiseModel,
    /// The inventory's spellings, sorted -- the candidate origins.
    syllables: Box<[Box<str>]>,
    /// `outcomes(y)` per inventory syllable, in `syllables` order, each in
    /// production order (see [`NoiseModel::outcomes`]).
    outcomes: Vec<Vec<(Box<str>, f64)>>,
    /// The strings that earn a cost-0 self entry: every syllable and every
    /// proper prefix of one.
    self_entries: HashSet<Box<str>>,
    /// Spans already resolved, by span.
    cache: RwLock<HashMap<Box<str>, std::sync::Arc<Resolved>>>,
    /// How many entries a list keeps.
    k: usize,
}

impl CorrectionTable {
    /// Build the table the embedded `typo.json` and *table*'s inventory
    /// describe.
    ///
    /// # Errors
    ///
    /// If the embedded table is malformed. A data error, not a runtime
    /// condition: `load` refuses it rather than correcting.
    pub fn load(table: &SyllableTable) -> Result<Self, NoiseError> {
        let model = NoiseModel::parse(TYPO_MODEL)?;
        let mut syllables: Vec<Box<str>> = Vec::with_capacity(table.len());
        let mut self_entries: HashSet<Box<str>> = HashSet::new();
        for syllable in table.prefix_range("") {
            let spelling = table.spelling(syllable);
            syllables.push(spelling.into());
            self_entries.insert(spelling.into());
            for length in 1..spelling.len() {
                self_entries.insert(spelling[..length].into());
            }
        }
        let outcomes = syllables
            .iter()
            .map(|syllable| model.outcomes(syllable))
            .collect();
        Ok(Self {
            model,
            syllables: syllables.into_boxed_slice(),
            outcomes,
            self_entries,
            cache: RwLock::new(HashMap::new()),
            k: CORRECTIONS_K,
        })
    }

    /// The `(syllable, cost)` entries for *span*, sorted then capped at `K`.
    ///
    /// # Panics
    ///
    /// If the memoisation lock is poisoned.
    #[must_use]
    pub fn corrections(&self, span: &str) -> std::sync::Arc<[Correction]> {
        std::sync::Arc::clone(&self.resolved(span).entries)
    }

    /// Every syllable's `-log P(span | y)` within two edits, by table index.
    ///
    /// The uncapped map `corrections` truncates to its `K` best: a candidate
    /// prior prices a character through the cheapest syllable that reads it,
    /// and that syllable need not have survived the cap.
    ///
    /// # Panics
    ///
    /// If the memoisation lock is poisoned.
    #[must_use]
    pub fn costs(&self, span: &str) -> std::sync::Arc<HashMap<usize, f64>> {
        std::sync::Arc::clone(&self.resolved(span).costs)
    }

    /// *span*'s [`Resolved`], memoised on first ask.
    ///
    /// # Panics
    ///
    /// If the memoisation lock is poisoned.
    fn resolved(&self, span: &str) -> std::sync::Arc<Resolved> {
        if let Some(cached) = self
            .cache
            .read()
            .expect("the corrections cache is not poisoned")
            .get(span)
        {
            return std::sync::Arc::clone(cached);
        }
        let resolved = std::sync::Arc::new(self.resolve(span));
        self.cache
            .write()
            .expect("the corrections cache is not poisoned")
            .insert(span.into(), std::sync::Arc::clone(&resolved));
        resolved
    }

    /// The uncached pass over *span*: every syllable the model can turn into it
    /// within two edits, each costed `-log P(span | y)`.
    fn resolve(&self, span: &str) -> Resolved {
        // `predecessors` is the exact inverse of `outcomes`, so the two-edit
        // paths into `span` are `y -> m -> span` with `m` a predecessor of
        // `span`; holding their probabilities once turns each syllable's share
        // into a lookup over its outcomes.
        let predecessors: HashMap<Box<str>, f64> = self
            .model
            .predecessors(span)
            .into_iter()
            .map(|middle| {
                let draw = self.model.one_edit_probability(&middle, span);
                (middle, draw)
            })
            .collect();
        let mut costs: HashMap<usize, f64> = HashMap::new();
        for (index, syllable) in self.syllables.iter().enumerate() {
            // Two edits move the length by at most two; outside that band no
            // path exists.
            if syllable.len() + 2 < span.len() || span.len() + 2 < syllable.len() {
                continue;
            }
            let outcomes = &self.outcomes[index];
            let mut probability = outcomes
                .iter()
                .find(|(produced, _)| produced.as_ref() == span)
                .map_or(0.0, |(_, draw)| *draw);
            for (intermediate, draw) in outcomes {
                if let Some(&second) = predecessors.get(intermediate.as_ref()) {
                    probability += draw * second;
                }
            }
            if probability > 0.0 {
                costs.insert(index, -probability.ln());
            }
        }
        // A span that is itself a syllable takes the cost-0 self entry in
        // place of whatever its own paths priced it at: the one slot then
        // reads `P(s | s) = 1`, matching `CorrectionTable._resolve_costs`. A
        // span that is only a prefix has no table index, so its self entry
        // is appended to the ranked list instead.
        let own = self
            .syllables
            .binary_search_by(|syllable| syllable.as_ref().cmp(span));
        if let Ok(index) = own {
            costs.insert(index, 0.0);
        }
        let mut ranked: Vec<Correction> = costs
            .iter()
            .map(|(&index, &cost)| Correction {
                span: self.syllables[index].clone(),
                cost,
            })
            .collect();
        if own.is_err() && self.self_entries.contains(span) {
            ranked.push(Correction {
                span: span.into(),
                cost: 0.0,
            });
        }
        ranked.sort_by(|a, b| a.cost.total_cmp(&b.cost).then_with(|| a.span.cmp(&b.span)));
        ranked.truncate(self.k);
        Resolved {
            entries: ranked.into(),
            costs: std::sync::Arc::new(costs),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_agrees_with_the_python_fixture() {
        let table = SyllableTable::load();
        let corrections = CorrectionTable::load(&table).expect("the noise table parses");
        let source = include_str!("../tests/fixtures/typo-corrections.json");
        let fixture: HashMap<String, Vec<(String, f64)>> =
            serde_json::from_str(source).expect("the fixture parses");
        for (span, want) in &fixture {
            let got = corrections.corrections(span);
            assert_eq!(
                got.len(),
                want.len(),
                "{span:?}: {} entries, want {}",
                got.len(),
                want.len()
            );
            for (index, (got, (syllable, cost))) in got.iter().zip(want).enumerate() {
                assert_eq!(
                    got.syllable(),
                    syllable,
                    "{span:?}[{index}]: got {:?}, want {syllable:?}",
                    got.syllable()
                );
                let delta = (got.cost() - cost).abs();
                assert!(
                    delta <= 1e-9 * cost.abs().max(1.0),
                    "{span:?}[{index}] {syllable:?}: got {}, want {cost}",
                    got.cost()
                );
            }
        }
    }
}
