"""The bridge's half of the contract: same order out as came in, and no guessing.

A score file names no characters. It is a rectangle of numbers whose only
meaning is the lattice it answers, so the two properties worth pinning are that
the rectangle has the shape the lattice asked for and that the number in each
slot belongs to the character that slot stands for. Both are checked against a
model small enough to build without a download.

The third property is that the module refuses rather than improvises. A
character the model has no row for is expected and takes the floor; a character
it *does* have a row for, offered at a position its own mask rules out, means
the two sides' pinyin tables have drifted and must raise.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import torch
from transformers import BertConfig

from mlime.train.emit import (
    CandidateIndex,
    LatticePath,
    LatticeRecord,
    examples_for,
    read_lattice,
    score_chunk,
)
from mlime.train.lexicon import Lexicon
from mlime.train.model import RouteAConfig, RouteAModel
from mlime.train.samples import BaseTokenizer, Collator
from mlime.train.spans import SpanVocab

TINY = BertConfig(
    vocab_size=256,
    hidden_size=32,
    num_hidden_layers=4,
    num_attention_heads=4,
    intermediate_size=64,
    max_position_embeddings=64,
)


@pytest.fixture(name="model")
def model_fixture(lexicon: Lexicon) -> RouteAModel:
    torch.manual_seed(0)
    model = RouteAModel.from_config(TINY, lexicon, RouteAConfig(cross_attention_layers=2))
    return model.eval()


def record(candidates: tuple[str, ...] = ("中钟重", "我")) -> LatticeRecord:
    """A two-position reading over the fixture lexicon's own characters."""
    return LatticeRecord(
        record=0,
        pinyin="zhongwo",
        context="北京",
        paths=(LatticePath(spans=("zhong", "wo"), candidates=candidates),),
    )


def test_a_lattice_line_parses_into_the_reading_it_describes() -> None:
    line = json.dumps(
        {
            "record": 4,
            "pinyin": "zhongwo",
            "context": None,
            "paths": [{"spans": ["zhong", "wo"], "candidates": ["中钟", "我"]}],
        }
    )
    parsed = LatticeRecord.parse(line)
    assert parsed.record == 4
    assert parsed.context is None
    assert parsed.paths[0].spans == ("zhong", "wo")
    assert parsed.paths[0].candidates == ("中钟", "我")


def test_a_lattice_line_with_an_unknown_field_is_refused() -> None:
    line = json.dumps({"record": 0, "pinyin": "wo", "paths": [], "weight": 2})
    with pytest.raises(ValueError, match="unknown fields"):
        LatticeRecord.parse(line)


def test_a_reading_whose_spans_and_positions_disagree_is_refused() -> None:
    with pytest.raises(ValueError, match="positions"):
        LatticePath(spans=("zhong", "wo"), candidates=("中钟",))


def test_a_position_the_model_can_say_nothing_about_is_allowed() -> None:
    path = LatticePath(spans=("zhong", "wo"), candidates=("", "我"))
    assert path.candidates[0] == ""


def test_a_lattice_file_streams_every_record(tmp_path: Path) -> None:
    path = tmp_path / "lattice.jsonl"
    lines = [
        json.dumps(
            {
                "record": index,
                "pinyin": "wo",
                "context": None,
                "paths": [{"spans": ["wo"], "candidates": ["我"]}],
            }
        )
        for index in range(3)
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    assert [item.record for item in read_lattice(path)] == [0, 1, 2]


def test_a_character_the_model_cannot_emit_is_a_lattice_disagreement(
    lexicon: Lexicon, spans: SpanVocab
) -> None:
    index = CandidateIndex(lexicon)
    # 種 is a zhong-reading character the fixture vocabulary does not hold, so a
    # lattice that asks about it was written against a different emittable set.
    with pytest.raises(ValueError, match="different emittable set"):
        index.resolve(spans.id("zhong"), "中種")


def test_a_character_the_span_does_not_admit_is_a_table_disagreement(
    lexicon: Lexicon, spans: SpanVocab
) -> None:
    index = CandidateIndex(lexicon)
    with pytest.raises(ValueError, match="not generated by the same run"):
        index.resolve(spans.id("wo"), "中")


def test_the_scores_come_back_in_the_order_the_lattice_asked(
    model: RouteAModel, lexicon: Lexicon, spans: SpanVocab, tokenizer: BaseTokenizer
) -> None:
    asked = record()
    scored = score_chunk(
        model,
        Collator(tokenizer, context_dropout=0.0),
        CandidateIndex(lexicon),
        [asked],
        spans,
        torch.device("cpu"),
        token_budget=256,
    )
    assert len(scored) == 1
    assert scored[0].record == 0
    paths = scored[0].paths
    assert len(paths) == 1
    assert [len(position) for position in paths[0]] == [3, 1]

    batch = Collator(tokenizer, context_dropout=0.0)(
        [example for _, example in examples_for(asked, spans)]
    )
    with torch.no_grad():
        logits = model(batch).logits.float()
    mask = model.candidate_mask[spans.id("zhong")]
    floor = torch.finfo(logits.dtype).min
    expected = logits[0, 1].masked_fill(~mask, floor).log_softmax(dim=-1)
    for slot, character in enumerate("中钟重"):
        assert paths[0][0][slot] == pytest.approx(
            float(expected[lexicon.index(character)]), abs=1e-4
        )


def test_a_position_with_nothing_emittable_is_scored_as_an_empty_row(
    model: RouteAModel, lexicon: Lexicon, spans: SpanVocab, tokenizer: BaseTokenizer
) -> None:
    scored = score_chunk(
        model,
        Collator(tokenizer, context_dropout=0.0),
        CandidateIndex(lexicon),
        [record(candidates=("", "我"))],
        spans,
        torch.device("cpu"),
        token_budget=256,
    )
    assert scored[0].paths[0] == [[], scored[0].paths[0][1]]
    assert len(scored[0].paths[0][1]) == 1
